apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-api
  namespace: team-platform
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - demo-api.platform.platform.internal
    secretName: demo-api-tls
  rules:
  - host: demo-api.platform.platform.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-api
            port:
              number: 80
